186 review and update  ready and  process method calls
project-viable/viable-virtual-lab pull request #204
Opened 2024-11-05 18:03 UTC by Drock54651

2024-11-05 18:50 UTC, harperstoeckle requested changes
By itself, the `super()` will directly call `_ready` in the base class. So `super()._ready()` will first call `_ready` in the base class, which returns `void`, then try to call `_ready` on the `void`, which will cause an error. So any instances of `super()._ready()` should be replaced with just `super()` or `super._ready()`. The former is shorter and idiomatic, so that's probably the best option.

2024-11-05 19:16 UTC, jakobrosencu commented
I second Harper

2024-11-06 03:24 UTC, Drock54651 commented
Good catch, seems like I was mixing it up with python syntax when I was doing super()._ready().

2024-11-06 06:13 UTC, harperstoeckle approved these changes

2024-11-06 16:23 UTC, AlexPhilipsen approved these changes

2024-11-06 20:37 UTC, maoc1414 approved these changes

2024-11-07 20:51 UTC, merged