Changed pressed to button_pressed
project-viable/viable-virtual-lab pull request #206
Opened 2024-11-06 17:13 UTC by AlexPhilipsen

There were no signals in the code base, however there was a single instance of pressed that did not get changed to button_pressed by the auto updater.

2024-11-06 21:21 UTC, harperstoeckle requested changes
`r`, `g`, and `b` in `Color` are `float`s between 0 and 1, so I think they should be `float`s. The `volume` parameter in `TakeContents` should also be a `float`. The various `content` variables (like `CurrContent`) seem to be `Substance`s.

2024-11-07 00:32 UTC, AlexPhilipsen commented
Thanks for catching those! For volume in `TakeContents` the editor says the parent definition is with `volume: int`.

2024-11-08 19:57 UTC, JRCockrum approved these changes

2024-11-08 23:37 UTC, harperstoeckle approved these changes

2024-11-08 23:37 UTC, merged