fixed errors in Menu.gd
project-viable/viable-virtual-lab pull request #215
Opened 2024-11-12 21:25 UTC by JRCockrum

2024-11-12 22:10 UTC, jakobrosencu commented
Currently merge conflicts. Can you fix these locally?

2024-11-12 22:15 UTC, jakobrosencu requested changes
Fix merge conflict locally. Merging dev into the branch and then resolving there should work

2024-11-13 00:49 UTC, harperstoeckle approved these changes

2024-11-13 21:57 UTC, jakobrosencu approved these changes

2024-11-14 00:11 UTC, merged